name: desktop_window_utils
description: A plugin for you to control the windows, their properties and toolbar/titlebars.
version: 0.0.1
repository: https://github.com/salihgueler/desktop_window_utils

environment:
  sdk: ">=2.7.0 <3.0.0"
  flutter: ">=1.20.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    platforms:
      macos:
        pluginClass: DesktopWindowUtilsPlugin
